#!/bin/bash

program() {
    ../pysim/pySim-prog.py -p0 -a $PIN_ADM -n $OPERATOR -c $COUNTRY_CODE -x $MCC -y $MNC -m $SMSC -s $ICCID -i $IMSI --msisdn=$MSISDN -k $KI -o $OPC --acc=$ACC --ims-hdomain=$IMS_HDOMAIN --impi=$IMPI --impu=$IMPU
}

OPERATOR=UJA5G
COUNTRY_CODE=0
MCC=001
MNC=01
SMSC=0005555
ACC=0001
IMS_HDOMAIN=ims.mnc$MNC.mcc$MCC.3gppnetwork.org

if [ "$1" = "0" ]; then

    PIN_ADM=85903454
    ICCID=8988211000000535305
    IMSI=001010000053530
    MSISDN=
    KI=1B7F04D495107F31E8DF29E5514F28CA
    OPC=DD71BC1880AF9367E4A52ECABAC326FD
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "1" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "2" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "3" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "4" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "5" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "6" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "7" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "8" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "9" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "10" ]; then

    PIN_ADM=
    ICCID=
    IMSI=
    MSISDN=
    KI=
    OPC=
    IMPI=
    IMPU=
    
    program
    
    exit 1
fi

if [ "$1" = "11" ]; then

    echo $IMS_HDOMAIN
    
    exit 1
fi
