apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${METRICS_IP}:9090
    uid: ${GRAFANA_DATASOURCE_PROMETHEUS_UID}
    jsonData:
      httpMethod: POST      
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'Low' 
      timeInterval: 1s
