name: Docker srsran

on:
  push:
    paths:
      - srsran/Dockerfile_test
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: cd srsran && docker build -f Dockerfile_test --no-cache --force-rm -t juanluss31/docker_srsran:test .

      - name: Push Image
        run: docker push juanluss31/docker_srsran:test
