name: Docker open5gs

on:
  push:
    paths:
      - base/Dockerfile
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build the Docker image
        run: docker build . --file /base/Dockerfile --tag docker_open5gs:latest

      - name: Push Image
        run: docker push docker_open5gs:latest
